[package]
name = "rbtag_derive"
version = "0.1.0"
authors = ["Jeremy Mill <jeremy.mill@otis.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.24"
quote = "0.6.10"
chrono = "0.4.6"
proc-macro2 = "0.4.24"